export const GET_ALL_ACCESS_CONTROL_LIST = "ERP_HR_USERMANGEMENT_GET_ACCESS_CONTROL_LIST";
export const INPUT_CHANGED = "ERP_HR_USERMANGEMENT_ACCESS_CONTROL_INPUT_CHANGED";
export const SET_FORM = "ERP_HR_USERMANAGEMENT_ACCESS_CONTROL_SET_FORM";
export const ACCESS_CONTROL_CHANGED = "ERP_HR_USERMANAGEMENT_ACCESS_CONTROL_CHANGED";
export const UPDATE_ACCESS_CONTROL = "ERP_HR_USERMANAGEMENT_UPDATE_ACCESS_CONTROL";
export const TREE_NODE_SELECTED = "ERP_HR_USERMANAGEMENT_TREE_NODE_SELECTED";